; Application PHP configuration
date.timezone = UTC

memory_limit = 512M
max_execution_time = 120
max_input_time = 120

upload_max_filesize = 64M
post_max_size = 64M

expose_php = Off

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0